version: '3'
services:
  web:
    build: .  # build from Dockerfile in current directory
    ports:
      - "3000:5173"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
volumes:
  web:
